---
# file: devstacked-playbook.yml
# Playbook to deploy and configure the Vagrant DevStack environment

- name: devstack tasks
  hosts: devstack
  vars_files:
    - vars/local.yml

  roles:
    - devstack
