---
- stat: path={{ devstack_working_dir }}/unstack.sh
  register: unstack_script

- name: unstack an existing devstack
  sudo: true
  sudo_user: "{{ devstack_user }}"
  command: ./unstack.sh chdir={{ devstack_working_dir }}
  when: unstack_script.stat.exists == true and devstack_clean == false

- name: clean an existing devstack
  include: clean.yml
  when: devstack_clean == true

- name: clone the devstack repo
  sudo: true
  sudo_user: "{{ devstack_user }}"
  git: >
    repo={{ devstack_repo }}
    dest={{ devstack_working_dir }}
    version={{ devstack_version }}

- name: configure devstack
  sudo: true
  sudo_user: "{{ devstack_user }}"
  template: >
    src=local.conf.j2
    dest={{ devstack_working_dir }}/local.conf
    owner={{ devstack_user }}
    group={{ devstack_user }}

- name: stack devstack
  sudo: true
  sudo_user: "{{ devstack_user }}"
  command: ./stack.sh chdir={{ devstack_working_dir }}

- name: completed devstack setup
  debug: msg="dashboard available at http://{{ hostvars['devstack']['ansible_' + devstack_interface]['ipv4']['address'] }}/"
